const questions=[
{name:"name",
message: "Enter Employee Name",
},
{name:"id",
message: "Enter Employee Id",
},
{name: "email",
message: "Enter Employee Email",
},
{name: "employeeType",
type: "list",
message: "Which one are they?",
choices: ["Manager", "Engineer", "Intern"],
},
{name: "github",
message: "Enter Engineer Github Username",
when: (answers) => answers.employeeType === "Engineer",
},
{name: "officeNumber",
message: "Enter Manager's Office Number",
when: (answers) => answers.employeeType === "Manager",
},
{name: "school",
message: "Enter Intern's School",
when: (answers) => answers.employeeType === "Intern",
},
{name: "again",
message: "Do you want to add more employees?",
type: "confirm",
default: "true",
}

];
module.exports = questions;